# GRADING SYSTEM 
The project is about granding the students marks it prompts the user to key in marks

In [2]:
marks=int(input("Enter students marks: "))
if(marks>=70 and marks<=100):
    print("A")
elif(marks>=60):
    print("B")
elif(marks>=50):
    print("C")
elif(marks>=40):
    print("D")
else:
    print("FAIL")
if(marks>=40 and marks<=100):
     print('CONGRATULATIONS🎁🎁') 
else:
            print('YOU ARE JOKING')
    

Enter students marks: 39
FAIL
YOU ARE JOKING


# solving a quadratic equqtion
The project is about solving a quadratic equation usingthe  quadratic formula

In [43]:
from math import sqrt
a=float(input("Enter a:"))
b=float(input("Enter b:"))
c=float(input("Enter c:"))
d=b**2-(4*a*c)
if(d>0):
    A1=(-b+sqrt(d))/(2*a)
    A2=(-b-sqrt(d))/(2*a)
    print("Roots:",A1,A2)
    print("real roots")
elif(d==0):
    B=-b/(2*a)
    print("Root:",B)
    print("equal root")
elif(d<0):
    E1=(-b+sqrt(abs(d)))/(2*a)
    E2=(-b-sqrt(abs(d)))/(2*a)
    print("Root:",E1,E2)
    print("complex roots")
else:
    print("this is not a quadratic equation")

    
    


Enter a:5
Enter b:9
Enter c:2
Roots: -0.2596875762567151 -1.5403124237432848
real roots


In [5]:
age=int(input("Enter your age:"))
if age<18:
    print("GO AWAY,you are a child")
elif age>=18:
    print("welcome AT YOUR OWN RISK")


Enter your age:12
GO AWAY,you are a child


In [ ]:
from math import sqrt
a=float(input("Enter a:"))
b=float(input("Enter b:"))
c=float(input("Enter c:"))
d=b**2-(4*a*c)
if(d>0):
    A1=(-b+sqrt(d))/(2*a)
    A2=(-b-sqrt(d))/(2*a)
    print("Roots:",A1,A2)
elif(d<0):
    E1=(-b+sqrt(abs(d)))/(2*a)
    E2=(-b-sqrt(abs(d)))/(2*a)
    print("Root:",E1,E2)
else:
    print("this is not a quadratic equation")

    
    

In [8]:
def prestige(age):
    if age>=18:
        print("you are welcome")
    elif age<18:
        print("you are not allowed in since you are underage")
prestige(20)

you are welcome


In [3]:
age=int(input("how old are you:"))
def prestige(age):
    if age>=18:
        print("you are welcome")
    elif age<18:
        print("you are not allowed in since you are underage")
prestige(age)

how old are you:24
you are welcome


In [4]:

number = int(input("Enter a number: "))
if number % 2 == 0:
    print(number, "is an even number.")
else:
    print(number, "is an odd number.")

Enter a number: 17
17 is an odd number.


In [4]:
import numpy as np
samplearray=np.arange(100,200,10)
print(samplearray)
samplearray=samplearray.reshape(5,2)
print(samplearray)

[100 110 120 130 140 150 160 170 180 190]
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [6]:
import numpy as np
x=np.empty((3,4))
print(x)


[[1.07212798e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 2.46567317e+179 6.81639068e-091 1.42023802e+161]
 [1.00525363e-047 4.27696990e-037 3.99910963e+252 1.46030983e-319]]


In [4]:
import numpy as np
p=[[1,2],[2,3]]
q=[[4,5],[6,7]]
print(p)
print(q)
result=np.dot(p,q)
print(result)

[[1, 2], [2, 3]]
[[4, 5], [6, 7]]
[[16 19]
 [26 31]]


In [13]:
import numpy as np
from numpy.linalg import eig
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(A)
w,v=eig(a)
print('E-value:',w)
print('E-vector:',v)
inc=np.linalg.inv(A)
d=np.linalg.det(A)
print(d)
print(inc)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-1.820448242817726e-31
[[ 1.50119988e+15 -3.75299969e+14 -3.75299969e+15  2.62709978e+15]
 [-1.95155984e+16  1.95155984e+16  1.95155984e+16 -1.95155984e+16]
 [ 3.45275971e+16 -3.79052969e+16 -2.77721977e+16  3.11498974e+16]
 [-1.65131986e+16  1.87649984e+16  1.20095990e+16 -1.42613988e+16]]


In [12]:
a=int(input("Enter any number:"))
b=0
for x in range(0,a,2):
    b=+x
if x%2==0:
    print(x*10)
else:
    print(x)
print(b)

Enter any number:40
380
38


In [3]:
import numpy as np
A=np.zeros(10)
print(A)
C=np.ones(10)
print(C)
B=np.ones(10)*5
print(B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [1]:
F=input("ENTER YOUR NAME\ln")
print(f"my name is {F}")
age=[19,23,12,9,37,27]
for age_no in age:
    print(Age={age_no
    

ENTER YOUR NAME\lnALVIN
my name is ALVIN
Age=19
Age=23
Age=12
Age=9
Age=37
Age=27
