In [45]:
t=22
print(t)
print("JACKSON")
pi=3.142netsh
radius=7
area=pi*radius
print(area)
fname="jane"
lname="kelly"
print(fname+lname)
F=input("ENTER YOUR NAME\ln")
print(f"my name is {F}")
age=[19,23,12,9,37,27]
for age_no in age:
    print(f"Age={age_no}")

22
JACKSON
21.994
janekelly
ENTER YOUR NAME\lnJACK
my name is JACK
Age=19
Age=23
Age=12
Age=9
Age=37
Age=27


In [3]:
n=10
while True:
    print(n)
    n=n-1
    if n==5:
        break

10
9
8
7
6


In [15]:
data=["Apple","banana","mango"]
print(data)
for mango in data:
    print(mango)
print (data[0])
print (data[:2])
data.append("orange")
print(data)

['Apple', 'banana', 'mango']
Apple
banana
mango
Apple
['Apple', 'banana']
['Apple', 'banana', 'mango', 'orange']


In [18]:
details={"Name":"Kelly","Age":22}
print(details)
for key,value in details.items():
    print(f"{key}:{value}")

{'Name': 'Kelly', 'Age': 22}
Name:Kelly
Age:22


In [21]:
age=int(input("Enter your age\n"))
if age>=18:
    print("eligible to vote")
elif age<18:
    print("not eligible")
else:
    print("invalid input")

Enter your age
45
eligible to vote


In [5]:
def square_number(x):
    return x*x
print(square_number(4))

16


In [8]:
def calculator(a,b):
    add=a+b
    return add 
a=int(input("value of a:\n"))
b=int(input("value of b:\n"))
result=calculator(a,b)
print(result)

value of a:
4
value of b:
7
11


In [2]:
def squares_list(nums):
    squares=[]
    for num in nums:
        sq=num**2
        squares.append(sq)
        return squares
    print(squares_list([45,66,77]))

    

In [16]:
text='''Microsoft Cares About You'''

In [17]:
with open("details.text", "w") as file:
    file.write(text) 

In [3]:
text='''Microsoft Cares Your'''

In [4]:
text='''Microsoft Cares Your'''

In [5]:
with open("details.text", "r") as file:
    file.read(text)
    

TypeError: argument should be integer or None, not 'str'

In [6]:
import pandas as pd
import numpy as np


In [5]:
df_dict={'bob':[32,34,67,89],
'anne':[32,34,67,89],
'james':[32,34,67,89],
'jack':[32,34,67,89]}
    


In [7]:
import pandas as pd
data=pd.read_csv("Black_friday.csv")
data

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000004  P00128942      M  46-50           7             B   
1       1000009  P00113442      M  26-35          17             C   
2       1000010  P00288442      F  36-45           1             B   
3       1000010  P00145342      F  36-45           1             B   
4       1000011  P00053842      F  26-35           1             C   
...         ...        ...    ...    ...         ...           ...   
233594  1006036  P00118942      F  26-35          15             B   
233595  1006036  P00254642      F  26-35          15             B   
233596  1006036  P00031842      F  26-35          15             B   
233597  1006037  P00124742      F  46-50           1             C   
233598  1006039  P00316642      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               1                   1   
1                               0               0                   3   
2                              4+               1                   5   
3                              4+               1                   4   
4                               1               0                   4   
...                           ...             ...                 ...   
233594                         4+               1                   8   
233595                         4+               1                   5   
233596                         4+               1                   1   
233597                         4+               0                  10   
233598                         4+               1                   4   

        Product_Category_2  Product_Category_3  
0                     11.0                 NaN  
1                      5.0                 NaN  
2                     14.0                 NaN  
3                      9.0                 NaN  
4                      5.0                12.0  
...                    ...                 ...  
233594                 NaN                 NaN  
233595                 8.0                 NaN  
233596                 5.0                12.0  
233597                16.0                 NaN  
233598                 5.0                 NaN  

[233599 rows x 11 columns]

In [12]:
data.describe()

User_ID     Occupation  Marital_Status  Product_Category_1  \
count  2.335990e+05  233599.000000   233599.000000       233599.000000   
mean   1.003029e+06       8.085407        0.410070            5.276542   
std    1.726505e+03       6.521146        0.491847            3.736380   
min    1.000001e+06       0.000000        0.000000            1.000000   
25%    1.001527e+06       2.000000        0.000000            1.000000   
50%    1.003070e+06       7.000000        0.000000            5.000000   
75%    1.004477e+06      14.000000        1.000000            8.000000   
max    1.006040e+06      20.000000        1.000000           18.000000   

       Product_Category_2  Product_Category_3  
count       161255.000000        71037.000000  
mean             9.849586           12.669454  
std              5.094943            4.125944  
min              2.000000            3.000000  
25%              5.000000            9.000000  
50%              9.000000           14.000000  
75%             15.000000           16.000000  
max             18.000000           18.000000

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233599 entries, 0 to 233598
Data columns (total 11 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     233599 non-null  int64  
 1   Product_ID                  233599 non-null  object 
 2   Gender                      233599 non-null  object 
 3   Age                         233599 non-null  object 
 4   Occupation                  233599 non-null  int64  
 5   City_Category               233599 non-null  object 
 6   Stay_In_Current_City_Years  233599 non-null  object 
 7   Marital_Status              233599 non-null  int64  
 8   Product_Category_1          233599 non-null  int64  
 9   Product_Category_2          161255 non-null  float64
 10  Product_Category_3          71037 non-null   float64
dtypes: float64(2), int64(4), object(5)
memory usage: 19.6+ MB


In [14]:
data.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2             72344
Product_Category_3            162562
dtype: int64

In [15]:
data.nunique()

User_ID                       5891
Product_ID                    3491
Gender                           2
Age                              7
Occupation                      21
City_Category                    3
Stay_In_Current_City_Years       5
Marital_Status                   2
Product_Category_1              18
Product_Category_2              17
Product_Category_3              15
dtype: int64

In [16]:
data.T

0          1          2          3       \
User_ID                       1000004    1000009    1000010    1000010   
Product_ID                  P00128942  P00113442  P00288442  P00145342   
Gender                              M          M          F          F   
Age                             46-50      26-35      36-45      36-45   
Occupation                          7         17          1          1   
City_Category                       B          C          B          B   
Stay_In_Current_City_Years          2          0         4+         4+   
Marital_Status                      1          0          1          1   
Product_Category_1                  1          3          5          4   
Product_Category_2               11.0        5.0       14.0        9.0   
Product_Category_3                NaN        NaN        NaN        NaN   

                               4          5          6         7       \
User_ID                       1000011    1000013    1000013   1000013   
Product_ID                  P00053842  P00350442  P00155442  P0094542   
Gender                              F          M          M         M   
Age                             26-35      46-50      46-50     46-50   
Occupation                          1          1          1         1   
City_Category                       C          C          C         C   
Stay_In_Current_City_Years          1          3          3         3   
Marital_Status                      0          1          1         1   
Product_Category_1                  4          2          1         2   
Product_Category_2                5.0        3.0       11.0       4.0   
Product_Category_3               12.0       15.0       15.0       9.0   

                               8          9       ...     233589     233590  \
User_ID                       1000015    1000022  ...    1006030    1006032   
Product_ID                  P00161842  P00067942  ...  P00241442  P00252442   
Gender                              M          M  ...          M          M   
Age                             26-35      18-25  ...      26-35      46-50   
Occupation                          7         15  ...         17          7   
City_Category                       A          A  ...          C          A   
Stay_In_Current_City_Years          1         4+  ...          1          3   
Marital_Status                      0          0  ...          1          0   
Product_Category_1                 10          5  ...          2          8   
Product_Category_2               13.0       14.0  ...       15.0        NaN   
Product_Category_3               16.0        NaN  ...        NaN        NaN   

                               233591     233592     233593     233594  \
User_ID                       1006033    1006035    1006036    1006036   
Product_ID                  P00127642  P00135742  P00255442  P00118942   
Gender                              M          F          F          F   
Age                             51-55      26-35      26-35      26-35   
Occupation                         13          1         15         15   
City_Category                       B          C          B          B   
Stay_In_Current_City_Years          1          3         4+         4+   
Marital_Status                      1          0          1          1   
Product_Category_1                  1          6          8          8   
Product_Category_2                2.0        8.0        NaN        NaN   
Product_Category_3               15.0        NaN        NaN        NaN   

                               233595     233596     233597     233598  
User_ID                       1006036    1006036    1006037    1006039  
Product_ID                  P00254642  P00031842  P00124742  P00316642  
Gender                              F          F          F          F  
Age                             26-35      26-35      46-50      46-50  
Occupation                         15         15          1   

In [18]:
data.sort_index(ascending=False)

User_ID Product_ID Gender    Age  Occupation City_Category  \
233598  1006039  P00316642      F  46-50           0             B   
233597  1006037  P00124742      F  46-50           1             C   
233596  1006036  P00031842      F  26-35          15             B   
233595  1006036  P00254642      F  26-35          15             B   
233594  1006036  P00118942      F  26-35          15             B   
...         ...        ...    ...    ...         ...           ...   
4       1000011  P00053842      F  26-35           1             C   
3       1000010  P00145342      F  36-45           1             B   
2       1000010  P00288442      F  36-45           1             B   
1       1000009  P00113442      M  26-35          17             C   
0       1000004  P00128942      M  46-50           7             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
233598                         4+               1                   4   
233597                         4+               0                  10   
233596                         4+               1                   1   
233595                         4+               1                   5   
233594                         4+               1                   8   
...                           ...             ...                 ...   
4                               1               0                   4   
3                              4+               1                   4   
2                              4+               1                   5   
1                               0               0                   3   
0                               2               1                   1   

        Product_Category_2  Product_Category_3  
233598                 5.0                 NaN  
233597                16.0                 NaN  
233596                 5.0                12.0  
233595                 8.0                 NaN  
233594                 NaN                 NaN  
...                    ...                 ...  
4                      5.0                12.0  
3                      9.0                 NaN  
2                     14.0                 NaN  
1                      5.0                 NaN  
0                     11.0                 NaN  

[233599 rows x 11 columns]

In [20]:
data.sort_values(by="Age")

User_ID Product_ID Gender   Age  Occupation City_Category  \
98919   1002288  P00127642      M  0-17          10             B   
178852  1005524  P00249142      F  0-17          10             B   
20745   1002042  P00241442      M  0-17          10             C   
93911   1000753  P00075642      M  0-17          10             C   
93910   1000753  P00116742      M  0-17          10             C   
...         ...        ...    ...   ...         ...           ...   
147760  1005313  P00346242      M   55+           0             A   
219148  1001870  P00026042      M   55+          13             C   
106713  1002297  P00003442      M   55+          13             C   
201827  1005273  P00100142      M   55+          20             B   
156177  1000444  P00318742      M   55+           0             A   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
98919                           2               0                   1   
178852                          1               0                   5   
20745                          4+               0                   2   
93911                           1               0                   4   
93910                           1               0                  11   
...                           ...             ...                 ...   
147760                          3               0                   1   
219148                          1               0                   8   
106713                         4+               1                   4   
201827                          3               1                  10   
156177                          3               0                   1   

        Product_Category_2  Product_Category_3  
98919                  2.0                15.0  
178852                 NaN                 NaN  
20745                 15.0                 NaN  
93911                  5.0                 NaN  
93910                  NaN                 NaN  
...                    ...                 ...  
147760                15.0                 NaN  
219148                14.0                17.0  
106713                 5.0                 8.0  
201827                16.0                 NaN  
156177                 8.0                 NaN  

[233599 rows x 11 columns]

In [25]:
data.Age.unique()

array(['46-50', '26-35', '36-45', '18-25', '51-55', '55+', '0-17'],
      dtype=object)

In [43]:
data.Age.nunique()

7

In [27]:
data.groupby('Age').mean(numeric_only=True)

User_ID  Occupation  Marital_Status  Product_Category_1  \
Age                                                                   
0-17   1.002745e+06    8.852856        0.000000            4.933408   
18-25  1.002799e+06    6.734826        0.213179            4.983709   
26-35  1.003114e+06    7.916652        0.395213            5.212559   
36-45  1.003067e+06    8.846118        0.392242            5.365738   
46-50  1.003178e+06    8.580937        0.718292            5.584972   
51-55  1.002984e+06    8.687650        0.722840            5.606276   
55+    1.002990e+06    9.524848        0.627879            5.819504   

       Product_Category_2  Product_Category_3  
Age                                            
0-17             9.048526           11.868580  
18-25            9.456385           12.432550  
26-35            9.823506           12.625110  
36-45            9.968574           12.764458  
46-50           10.179712           12.932203  
51-55           10.263990           13.020111  
55+             10.486561           13.272946

In [29]:
data.loc[[200000]]

User_ID Product_ID Gender    Age  Occupation City_Category  \
200000  1002274  P00190642      M  18-25           2             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
200000                          3               0                   8   

        Product_Category_2  Product_Category_3  
200000                 9.0                 NaN

In [31]:
data.loc[233000,'Gender']

'M'

In [39]:
data.iloc[233000,3]

'46-50'

DATA CLEANING

In [45]:
data.Age=data.Age.str.lstrip('+')

In [2]:
import numpy as np

In [3]:
a1=np.array([22,55,66,77])
a1

array([22, 55, 66, 77])

In [7]:
a2_a2=np.array([[22,55,66,77],[778,34,998,776]])
a2_a2


array([[ 22,  55,  66,  77],
       [778,  34, 998, 776]])

In [8]:
a1.shape

(4,)

In [9]:
a1.ndim

1

In [10]:
a2_a2.shape

(2, 4)

In [11]:
a2_a2.ndim

2

In [13]:
a2=np.zeros((3,2))
a2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
a3=np.ones(shape=(5,3))
a3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#using linspace 

In [17]:
a4=np.linspace(0,100,10)
a4

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [18]:
#using np.arange

In [20]:
a5=np.arange(0,100,5)
a5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [21]:
a6=np.full((5,4),"python")
a6

array([['python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python']], dtype='<U6')

In [23]:
a6[3,2]='clearance'
a6

array([['python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python'],
       ['python', 'python', 'cleara', 'python'],
       ['python', 'python', 'python', 'python']], dtype='<U6')

In [25]:
np.euler_gamma

0.5772156649015329

In [30]:
np.pi

3.141592653589793

In [26]:
np.e

2.718281828459045

In [27]:
np.inf

inf

In [28]:
np.NINF

-inf

In [29]:
np.inf==np.NINF

False

In [31]:
with your highschool reunion fast approaching, you decide to get i shape and lose some weight. 
You recordyour weight everyday for five weeks starting on monday. 
Given these daily weights, build an array with your average weights per weekend.

SyntaxError: invalid syntax (3731297206.py, line 1)

In [32]:
given_array=np.random.randint(50,78,(5,5))
given_array

array([[56, 52, 54, 69, 53],
       [65, 53, 56, 74, 52],
       [51, 75, 59, 54, 74],
       [73, 63, 59, 74, 73],
       [57, 51, 54, 61, 56]])

In [34]:
import pandas as pd
data=pd.DataFrame(data=given_array,index=['week1','week2','week3','week4','week5'])
data

0   1   2   3   4
week1  56  52  54  69  53
week2  65  53  56  74  52
week3  51  75  59  54  74
week4  73  63  59  74  73
week5  57  51  54  61  56

In [35]:
np.mean(data,axis=1)

week1    56.8
week2    60.0
week3    62.6
week4    68.4
week5    55.8
dtype: float64

In [36]:
array_1=np.random.randint(25,75,(5,3))
array_1

array([[35, 54, 39],
       [35, 50, 61],
       [65, 50, 70],
       [25, 56, 47],
       [70, 35, 31]])

In [37]:
np.reshape(array_1,(3,5))

array([[35, 54, 39, 35, 50],
       [61, 65, 50, 70, 25],
       [56, 47, 70, 35, 31]])

In [38]:
array_1

array([[35, 54, 39],
       [35, 50, 61],
       [65, 50, 70],
       [25, 56, 47],
       [70, 35, 31]])

In [39]:
np.shape(array_1,)

(5, 3)

In [47]:
array_1.shape = (3,5,)
array_1

array([[35, 54, 39, 35, 50],
       [61, 65, 50, 70, 25],
       [56, 47, 70, 35, 31]])

In [48]:
array_1

array([[35, 54, 39, 35, 50],
       [61, 65, 50, 70, 25],
       [56, 47, 70, 35, 31]])

In [50]:
array_1[1,1]

65

In [1]:
import pandas as pd
import numpy as np

In [3]:
D=pd.read_csv('breast-cancer.csv')
print(D)

           id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compa

In [30]:
A=pd.read_csv('Iris.csv')
print(A)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [31]:
A.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [32]:
A.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [11]:
B=pd.read_csv('diabetes.csv')
print(B)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  

In [12]:
B.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [13]:
B.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0